version: "3.1"

services:
  db:
    image: postgres:12
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  web:
    build:
      context: .
    depends_on:
      - db
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000

  adminer:
    image: adminer
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres-db:


